services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
    labels:
      org.springframework.boot.readiness-check.tcp.disable: true
  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - '9411'
    labels:
      org.springframework.boot.readiness-check.tcp.disable: true
  kafka:
    image: 'apache/kafka:latest'
    ports:
      - '9092'
    labels:
      org.springframework.boot.readiness-check.tcp.disable: true
  collector:
    image: 'otel/opentelemetry-collector-contrib:latest'
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    labels:
      org.springframework.boot.readiness-check.tcp.disable: true

