version: '3.40.0'

tasks:
  infra-up:
    desc: Setup infrastructure
    cmds:
      - docker-compose -f infra/docker/compose.yaml up -d
  infra-down:
    desc: Tear down infrastructure
    cmds:
      - docker-compose -f infra/docker/compose.yaml down
  build:
    desc: Build the project
    cmds:
      - ./mvnw clean package

  run:
    desc: Run the application
    cmds:
      - ./mvnw spring-boot:run

  test:
    desc: Run tests
    cmds:
      - ./mvnw test

  clean:
    desc: Clean the project
    cmds:
      - ./mvnw clean

  deps:
    desc: Display project dependencies
    cmds:
      - ./mvnw dependency:tree

  default:
    cmds:
      - task --list-all