version: '3.40.0'

tasks:
  build:
    desc: Build the project
    cmds:
      - ./mvnw clean package

  run:
    desc: Run the application
    cmds:
      - ./mvnw spring-boot:run

  test:
    desc: Run tests
    cmds:
      - ./mvnw test

  clean:
    desc: Clean the project
    cmds:
      - ./mvnw clean

  deps:
    desc: Display project dependencies
    cmds:
      - ./mvnw dependency:tree

  default:
    cmds:
      - task --list-all