management:
  health:
    circuitbreakers:
      enabled: true
  tracing.sampling.probability: 1.0
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      sla:
        http.server.requests: 1ms,5ms
  endpoint:
    env:
      show-values: ALWAYS
    configprops:
      show-values: ALWAYS
    health:
      show-details: ALWAYS
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    java:
      enabled: true
    git:
      enabled: true
      mode: full
    os:
      enabled: true
    env:
      enabled: true

resilience4j.retry:
  instances:
    backendA:
      maxAttempts: 3
      waitDuration: 100ms
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - java.lang.RuntimeException
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 10
      waitDurationInOpenState: 10000
      failureRateThreshold: 60
      eventConsumerBufferSize: 10
      registerHealthIndicator: true
    someShared:
      slidingWindowSize: 50
      permittedNumberOfCallsInHalfOpenState: 10
  instances:
    backendA:
      baseConfig: default
      waitDurationInOpenState: 5000
application.client:
  inventory:
    baseUrl: "http://test.com"
    connectTimeout: 1s